# Generated by Django 4.1 on 2022-10-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
